name: Lint

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 13.12.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.12.0

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

